
CREATE DATABASE IF NOT EXISTS e-commerce;
USE e-commerce;

CREATE TABLE CLIENT (
    ID_client INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(25) NOT NULL,
    Prenom VARCHAR(25) NOT NULL,
    Adresse VARCHAR(50),
    Ville VARCHAR(25),
    CodePostal INTEGER,
    Email VARCHAR(25) NOT NULL UNIQUE,
    MDP VARCHAR(25) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE ADMIN (
    ID_Admin INTEGER PRIMARY KEY AUTO_INCREMENT,
    nom_utilisateur VARCHAR(25) NOT NULL,
    email VARCHAR(25) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(25) NOT NULL,
    role VARCHAR(25) NOT NULL,
    date_creation DATE NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE CATEGORIE (
    ID_categories INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(25) NOT NULL,
    Description TEXT,
    Image VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PRODUIT (
    ID_Produit INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    Description TEXT,
    Prix DECIMAL(10, 2) NOT NULL,
    Stock INTEGER NOT NULL DEFAULT 0,
    Image VARCHAR(50),
    Actif BOOLEAN,
    ID_categorie INTEGER,
    ID_Admin INTEGER,
    FOREIGN KEY (ID_categorie) REFERENCES CATEGORIE(ID_categories) ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (ID_Admin) REFERENCES ADMIN(ID_Admin) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);




CREATE TABLE COMMANDE (
    ID_Commande INTEGER PRIMARY KEY AUTO_INCREMENT,
    Statut VARCHAR(50) NOT NULL,
    Prix_total DECIMAL(10, 2) NOT NULL DEFAULT 0,
    ID_client INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_client) REFERENCES CLIENT(ID_client) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE LIGNE_DE_COMMANDE (
    ID_Ligne INTEGER PRIMARY KEY AUTO_INCREMENT,
    Quantite INTEGER NOT NULL,
    Prix_Unitaire DECIMAL(10, 2) NOT NULL,
    Sous_total DECIMAL(10, 2) NOT NULL,
    ID_Commande INTEGER NOT NULL,
    ID_Produit INTEGER NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_Commande) REFERENCES COMMANDE(ID_Commande) ON DELETE CASCADE,
    FOREIGN KEY (ID_Produit) REFERENCES PRODUIT(ID_Produit) ON DELETE CASCADE
);


CREATE INDEX client_email ON CLIENT(Email);
CREATE INDEX client_adresse ON CLIENT(Adresse, CodePostal, Ville);

CREATE INDEX admin_email ON ADMIN(email);
CREATE INDEX admin_role ON ADMIN(role);

CREATE INDEX categorie_nom ON CATEGORIE(Nom);

CREATE INDEX produit_nom ON PRODUIT(Nom);
CREATE INDEX produit_categorie ON PRODUIT(ID_categorie);
CREATE INDEX produit_actif ON PRODUIT(Actif);
CREATE INDEX produit_prix ON PRODUIT(Prix);

CREATE INDEX commande_client ON COMMANDE(ID_client);
CREATE INDEX commande_statut ON COMMANDE(Statut);
CREATE INDEX commande_date ON COMMANDE(created_at);

CREATE INDEX ligne_commande ON LIGNE_DE_COMMANDE(ID_Commande);
CREATE INDEX ligne_produit ON LIGNE_DE_COMMANDE(ID_Produit);



ALTER TABLE CLIENT ADD CONSTRAINT chk_codepostal CHECK (CodePostal >= 10000 AND CodePostal <= 99999);
ALTER TABLE PRODUIT ADD CONSTRAINT chk_prix CHECK (Prix >= 0);
ALTER TABLE COMMANDE ADD CONSTRAINT chk_prix_total CHECK (Prix_total >= 0);
ALTER TABLE LIGNE_DE_COMMANDE ADD CONSTRAINT chk_quantite CHECK (Quantite > 0);
ALTER TABLE LIGNE_DE_COMMANDE ADD CONSTRAINT chk_prix_unitaire CHECK (Prix_Unitaire >= 0);
ALTER TABLE LIGNE_DE_COMMANDE ADD CONSTRAINT chk_sous_total CHECK (Sous_total >= 0);





